name: 'Laravel Zero Downtime Deployment'
description: 'Deploy project to server by ssh with zero downtime deployment.'

inputs:
  host:
    description: 'Remote server host ex: 192.168.0.1 or localhost.com'
    required: true
  username:
    description: 'Remote server username ex: github-action'
    required: true
  port:
    description: 'Remote server port default: 22'
    required: true
  password:
    description: 'Remote server password'
    required: false
  ssh_key:
    description: 'SSH private key to connect server instead use password'
    required: false
  target:
    description: 'Remote server target path '
    required: true
  sha:
    description: 'Git commit sha need to deploy (github.sha)'
    required: true
  github_token:
    description: 'Github token'
    required: true
  env_file:
    description: 'Environment file content to sync with .env file'
    required: false


  command_script_before_check_folders:
    description: 'Command script before checking folders'
    required: false
    default: 'false'
  command_script_after_check_folders:
    description: 'Command script after checking folders'
    required: false
    default: 'false'
  command_script_before_download:
    description: 'Command script before download release'
    required: false
    default: 'false'
  command_script_after_download:
    description: 'Command script after download release'
    required: false
    default: 'false'
  command_script_before_activate:
    description: 'Command script before activate release'
    required: false
    default: 'false'
  command_script_after_activate:
    description: 'Command script after activate release'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: "upload-cloud"
  color: "black"