name: Build and Compile code modules

on:
  push:
    branches:
      - main
  release:
    types: [released]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Install ncc
      run: npm install -g @vercel/ncc

    - name: Build
      run: npm run build

    - name: Commit Build changes 
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main
        commit_message: 'Build Action ${{ github.sha }}'
        file_pattern: '.'